import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import ProgressBar from "@/components/global/ProgressBar";
import { CartProvider } from "@/context/CartContext";

const inter = Inter({
  subsets: ["latin"],  
  display: "swap",
});

export const metadata: Metadata = {
  title: "Varnikaa Cafe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        {/* <ProgressBar /> */}
        <Toaster />
        <CartProvider>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
